### ISSUE TITLE
Implementation of Block Factory

### ISSUE THREAD

**Issue by LuisHurtadoXO** [Software-Eng-9e/demo-repository#1]
As a teacher, I would like to make custom blocks for my students to use so they can learn how to adapt other’s code as well as them to be able to make their own custom code.

**Acceptance Criteria Checklist:** 
- [x] The teacher can generate a template or stub for the custom block, defining its name, input parameters, and expected outputs.
- [x] The block factory blocks and displays properly interact with each other to display information from the user changes.
- [x] A preview of the Arduino code is displayed and dynamically responds to changes in the toolbox.

**Task Checklist:**
- [x] Custom Block preview
- [x] Generator Stub
- [x] Custom Block Definition
- [x] Expected Display
