### ISSUE TITLE
Synchronous Blockly Experience That Exceeds Other Current Implementations

### ISSUE THREAD

**Issue by MateusSalavC** [Software-Eng-9e/demo-repository#13]
As a user, I would like to be able to have a complete and comprehensive Blockly experience that compares to current iterations of the base code.

**Acceptance Criteria Checklist:** 
- [x] block factory is implemented on the casmm.org website in a preferred format.
- [x] Seamless integration of block factory functionality and easy access for users.

**Task Checklist:**
- [x] Find Similar Code Base(s)
- [x] Understand Code Translator Feature within Similar Codebase
- [x] Import Ardublockly and google blockly features.
