### ISSUE TITLE
Save Custom Block

### ISSUE THREAD

**Issue by connor-r-haley** [Software-Eng-9e/demo-repository#15]
As a teacher, upon selecting the ‘Save Custom Block’ button, the Custom Block information is stored in an appropriate container and the container should be usable across the project as a list of the saved blocks.

**Acceptance Criteria Checklist:**
- [x] Upon clicking the button, the user is prompted to add a description of the block that the students will see.
- [x] The saved blocks are able to be saved by the teacher.
- [ ] The saved blocks are able to be used by the students.

**Task Checklist:**
- [x] Implement Clicking Functionality within the Save Block
- [x] Prompt User for (Name &) Description
- [x] Store Name and Description
- [ ] Store Block Definition and Generator Stub (dependent upon XML conversion).
- [ ] Connect to Strapi
- [ ] Make Accessible to Students
