### ISSUE TITLE
Documentation for Blocks

### ISSUE THREAD

**Issue by LuisHurtadoXO** [Software-Eng-9e/demo-repository#2]
As a user, I want clear documentation when creating custom blocks so I can utilize the features within the external libraries without confusion.

**Acceptance Criteria Checklist:**
- [x] When creating a custom block, the factory should prompt the user to write documentation for the custom block
- [ ] Documentation should be displayed in the custom block list tab.

**Task Checklist:**
- [x] Request for documentation
- [ ] Proper display
