### ISSUE TITLE
Adaptable Toolbox

### ISSUE THREAD

**Issue by LuisHurtadoXO** [Software-Eng-9e/demo-repository#3]
As a teacher, I want to have easy access to the block factory and to be able to easily switch between the block factory and Arduino canvas. I also want the code-sparks toolbox to adapt to the block factory functionalities.

**Acceptance Criteria Checklist:**
- [x] Be able to seamlessly transition between the Arduino canvas and custom block factory. Have easy access to block factory blocks and block factory root toolbox.

**Task Checklist:**
- [x] Proper factory blocks loading and unloading
- [x] block factory root block usable in canvas
- [x]  Immediate feedback from toolbox interaction
