### ISSUE TITLE
Sharing Blocks in the Gallery

### ISSUE THREAD

**Issue by LuisHurtadoXO** [Software-Eng-9e/demo-repository#4]
As a student, I want easy access to the galleries to utilize the custom blocks created by others in the current project I am working on. 
Students can access and implement blocks within the gallery in their workspace

**Acceptance Criteria Checklist:**
- [ ] Verify that students can easily access and utilize custom blocks created by others in their current projects.
- [ ] Students can access and implement blocks within the gallery in their workspace

**Task Checklist:**
- [ ] Share Button
- [ ] Connection to Gallery
- [ ] Watch Tutorials
