### ISSUE TITLE
Utilizing Custom Blocks in the Workspace & Classroom

### ISSUE THREAD

**Issue by LuisHurtadoXO** [Software-Eng-9e/demo-repository#5]
As a teacher, I want to be able to create custom blocks within the app, so I can tailor coding experiences for my students in an interactive way.
Teachers are able to create a custom block and upload it to the gallery

**Acceptance Criteria Checklist:**
- [x] Ensure that teachers can create custom blocks within the app.
- [ ] Verify that teachers can tailor coding experiences for their students in an interactive form.
- [ ] Confirm that teachers can upload custom blocks to the gallery for sharing.

**Task Checklist:**
- [ ] Import Button To Gallery
- [x] Import Functionality to Toolbox
- [x] Watch Tutorials
