### ISSUE TITLE
Block generator that Works Conveniently and Entirely Within CodeSparks

### ISSUE THREAD

**Issue by LuisHurtadoXO** [Software-Eng-9e/demo-repository#8]
As a user, I expect to be able to design my project, custom blocks, and access any and all libraries all within the codesparks website.
Generator that works seamlessly within the users’ preferred workspace

**Acceptance Criteria Checklist:**
- [x] Ensure that the block generator works seamlessly within the Codesparks website.
- [x]  users can create custom blocks within the Codesparks website.

**Task Checklist:**
- [x] Written Code to Block Translation
- [x] Functionality
- [x] Watch Tutorials
